name: Fortran code update

on:
  push:
    branches:
      - main
  schedule:
      - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nvidia/cuda:12.9.0-devel-ubuntu24.04

    timeout-minutes: 180
    steps:
      - name: Set timezone
        run: ln -fs /usr/share/zoneinfo/Europe/Helsinki /etc/localtime

      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get install -y apt-transport-https ca-certificates gnupg software-properties-common wget
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
          apt-add-repository 'deb https://apt.kitware.com/ubuntu/ noble main'
          apt-get update
          apt-get install -y cmake flex bison openmpi-bin libopenmpi-dev gfortran git python3 python3-numpy python3-pandas

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup
        shell: bash
        run: |
          git clone --recurse-submodules --remote https://github.com/pencil-code/pencil-code.git
          cd pencil-code

      - name: Samples
        shell: bash
        run: |
          cd pencil-code
          export PENCIL_USER=GPU_AUTOTEST
          source sourceme.sh || true
          cd samples/build-samples/sample0
          pc_build -f GNU-GCC_MPI+GNU-GCC_debug+GNU-GCC_GPU FFLAGS+=-O0
          make distclean
          rm -rf src/astaroth
          cd ../../..
          cd src/astaroth
          python3 update_fortran.py -p $PENCIL_HOME -s sample0
          cd ../..
          cd samples/build-samples/sample1
          pc_build -f GNU-GCC_MPI+GNU-GCC_debug+GNU-GCC_GPU FFLAGS+=-O0
          make distclean
          rm -rf src/astaroth
          cd ../../..
          cd src/astaroth
          python3 update_fortran.py -p $PENCIL_HOME -s sample1
          cd ../..
          cd samples/build-samples/sample2
          pc_build -f GNU-GCC_MPI+GNU-GCC_debug+GNU-GCC_GPU FFLAGS+=-O0
          make distclean
          rm -rf src/astaroth
          cd ../../..
          cd src/astaroth
          python3 update_fortran.py -p $PENCIL_HOME -s sample2
          cd ../..
          cd samples/build-samples/sample3
          pc_build -f GNU-GCC_MPI+GNU-GCC_debug+GNU-GCC_GPU FFLAGS+=-O0
          make distclean
          rm -rf src/astaroth
          cd ../../..
          cd src/astaroth
          python3 update_fortran.py -p $PENCIL_HOME -s sample3
          cd ../..
          cd samples/build-samples/sample4
          pc_build -f GNU-GCC_MPI+GNU-GCC_debug+GNU-GCC_GPU FFLAGS+=-O0
          make distclean
          rm -rf src/astaroth
          cd ../../..
          cd src/astaroth
          python3 update_fortran.py -p $PENCIL_HOME -s sample4
          cd ../..
          cd samples/build-samples/sample5
          pc_build -f GNU-GCC_MPI+GNU-GCC_debug+GNU-GCC_GPU FFLAGS+=-O0
          make distclean
          rm -rf src/astaroth
          cd ../../..
          cd src/astaroth
          python3 update_fortran.py -p $PENCIL_HOME -s sample5
          cd ../..
          cd samples/build-samples/sample6
          pc_build -f GNU-GCC_MPI+GNU-GCC_debug+GNU-GCC_GPU FFLAGS+=-O0
          make distclean
          rm -rf src/astaroth
          cd ../../..
          cd src/astaroth
          python3 update_fortran.py -p $PENCIL_HOME -s sample6
          cd ../..

      - name: CommitAndPush
        continue-on-error: true
        shell: bash
        run: |
          cd pencil-code
          git config --global user.email "touko.puro@aalto.fi"
          git config --global user.name "ToxPuro"
          git remote set-url origin https://ToxPuro:${{ secrets.PENCIL_PASSWORD }}@pencil-code.org/git/
          git add src/*.f90
          git add src/cparam_enum.h
          git add src/special/*.f90
          git commit -m"Automatic commit to keep code GPU-enabled"
          git push




